{% set name = "cirun" %}
{% set version = "0.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cirun-{{ version }}.tar.gz
  sha256: 00a83272bd1490a2311d98eccb4ada7ad0ecf9c2a9220c52ae46b3e680c62a77

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - cirun = cirun.main:app

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - hatch
    - hatchling
    - requests
    - rich
    - typer

test:
  imports:
    - cirun
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cirun/
  summary: Cirun Python Client
  dev_url: https://github.com/aktechlabs/cirun-docs
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - aktech
